package main

func LookupECO(eco string) string {
	if o, ok := ECOMap[eco]; ok {
		return eco + " " + o
	}
	return eco
}

var ECOMap = map[string]string{
	"A00":     "Polish (Sokolsky) Opening",
	"A01":     "Nimzovich-Larsen attack",
	"A02":     "Bird's opening",
	"A03":     "Bird's opening",
	"A04":     "Reti opening",
	"A05":     "Reti opening",
	"A06":     "Reti opening",
	"A07":     "Reti opening, King's Indian Attack (Barcza)",
	"A08":     "Reti opening, King's Indian Attack",
	"A09":     "Reti opening",
	"A10":     "English Opening",
	"A11":     "English Opening, Caro-Kann defensive system",
	"A12":     "English Opening, Caro-Kann defensive system",
	"A13":     "English Opening",
	"A14":     "English Opening, Neo-Catalan declined",
	"A15":     "English Opening, 1 ...Nf6 (Anglo-Indian defence)",
	"A16":     "English Opening",
	"A17":     "English Opening",
	"A18":     "English Opening, Mikenas-Carls variation",
	"A19":     "English Opening, Mikenas-Carls variation",
	"A20":     "English Opening",
	"A21":     "English Opening",
	"A22":     "English Opening",
	"A23":     "English Opening, Bremen system",
	"A24":     "English Opening, Bremen system",
	"A25":     "English Opening, Sicilian reversed",
	"A26":     "English Opening, closed system",
	"A27":     "English Opening, three knights system",
	"A28":     "English Opening, four knights system",
	"A29":     "English Opening, four knights system",
	"A30":     "English Opening, symmetrical variation",
	"A31":     "English Opening, symmetrical, Benoni formation",
	"A32":     "English Opening, symmetrical variation",
	"A33":     "English Opening, symmetrical variation",
	"A34":     "English Opening, symmetrical variation",
	"A35":     "English Opening, symmetrical variation",
	"A36":     "English Opening, symmetrical variation",
	"A37":     "English Opening, symmetrical variation",
	"A38":     "English Opening, symmetrical variation",
	"A39":     "English Opening, symmetrical variation, main line with d4",
	"A40":     "Queen's pawn",
	"A41":     "Queen's pawn",
	"A42":     "Modern defence, Averbakh system",
	"A43":     "Old Benoni defence",
	"A44":     "Old Benoni defence",
	"A45":     "Queen's pawn game",
	"A46":     "Queen's pawn game",
	"A47":     "Queen's Indian defence",
	"A48":     "King's Indian, East Indian defence",
	"A49":     "King's Indian, fianchetto without c4",
	"A50":     "Queen's pawn game",
	"A51":     "Budapest defence declined",
	"A52":     "Budapest defence",
	"A53":     "Old Indian defence",
	"A54":     "Old Indian, Ukranian variation",
	"A55":     "Old Indian, main line",
	"A56":     "Benoni defence",
	"A57":     "Benko gambit",
	"A58":     "Benko gambit accepted",
	"A59":     "Benko gambit, 7. e4",
	"A60-A79": "Benoni defence",
	"A80":     "Dutch",
	"A81":     "Dutch defence",
	"A82":     "Dutch, Staunton Gambit",
	"A83":     "Dutch, Staunton Gambit",
	"A84":     "Dutch defence",
	"A85":     "Dutch with c4 & Nc3",
	"A86":     "Dutch with c4 & g3",
	"A87":     "Dutch, Leningrad",
	"A88":     "Dutch, Leningrad",
	"A89":     "Dutch, Leningrad",
	"A90":     "Dutch defence",
	"A91":     "Dutch defence",
	"A92":     "Dutch defence",
	"A93":     "Dutch, stonewall, Botwinnik variation",
	"A94":     "Dutch, stonewall with Ba3",
	"A95":     "Dutch, stonewall with Nc3",
	"A96":     "Dutch, classical variation",
	"A97":     "Dutch, Ilyin-Genevsky variation",
	"A98":     "Dutch, Ilyin-Genevsky variation",
	"A99":     "Dutch, Ilyin-Genevsky variation",
	"B00":     "King's pawn opening",
	"B01":     "Scandinavian defence",
	"B02":     "Alekhine's defence",
	"B03":     "Alekhine's defence",
	"B04":     "Alekhine's defence, modern variation",
	"B05":     "Alekhine's defence, modern variation, 4 ...Bg4",
	"B06":     "Robatsch (modern) defence",
	"B07":     "Pirc defence",
	"B08":     "Pirc defence, classical (two knights) system",
	"B09":     "Pirc defence, Austrian attack",
	"B10":     "Caro-Kann defence",
	"B11":     "Caro-Kann, two knights, 3 ...Bg4",
	"B12":     "Caro-Kann defence",
	"B13":     "Caro-Kann, exchange variation",
	"B14":     "Caro-Kann, Panov-Botvinnik attack, 5 ...e6",
	"B15":     "Caro-Kann defence",
	"B16":     "Caro-Kann, Bronstein-Larsen variation",
	"B17":     "Caro-Kann, Steinitz variation",
	"B18":     "Caro-Kann, classical variation",
	"B19":     "Caro-Kann, classical, 7 ...Nd7",
	"B20":     "Sicilian defence",
	"B21":     "Sicilian defence, Grand Prix attack",
	"B22":     "Sicilian, Alapin's variation (2. c3)",
	"B23":     "Sicilian, closed",
	"B24":     "Sicilian, closed",
	"B25":     "Sicilian, closed",
	"B26":     "Sicilian, closed, 6. Be3",
	"B27":     "Sicilian defence",
	"B28":     "Sicilian, O'Kelly variation",
	"B29":     "Sicilian, Nimzovich-Rubinstein variation",
	"B30":     "Sicilian defence",
	"B31":     "Sicilian, Nimzovich-Rossolimo attack (with ...g6, without ...d6)",
	"B32":     "Sicilian defence",
	"B33":     "Sicilian defence",
	"B34":     "Sicilian defence, accelerated fianchetto, exchange variation",
	"B35":     "Sicilian defence, accelerated fianchetto, modern variation with Bc4",
	"B36":     "Sicilian defence, accelerated fianchetto, Maroczy bind",
	"B37":     "Sicilian defence, accelerated fianchetto, Maroczy bind, 5 ...Bg7",
	"B38":     "Sicilian defence, accelerated fianchetto, Maroczy bind, 6. Be3",
	"B39":     "Sicilian defence, accelerated fianchetto, Breyer variation",
	"B40":     "Sicilian defence",
	"B41":     "Sicilian, Kan variation",
	"B42":     "Sicilian, Kan variation, 5. Bd3",
	"B43":     "Sicilian, Kan variation, 5. Nc3",
	"B44":     "Sicilian, Kan variation",
	"B45":     "Sicilian, Taimanov variation",
	"B46":     "Sicilian, Taimanov variation",
	"B47":     "Sicilian, Taimanov (Bastrikov) variation",
	"B48":     "Sicilian, Taimanov variation",
	"B49":     "Sicilian, Taimanov variation",
	"B50":     "Sicilian",
	"B51":     "Sicilian, Canal-Sokolsky",
	"B52":     "Sicilian, Canal-Sokolsky",
	"B53":     "Sicilian, Chekhover variation",
	"B54":     "Sicilian",
	"B55":     "Sicilian, Prins variation, Venice attack",
	"B56":     "Sicilian",
	"B57":     "Sicilian, Sozin, not Scheveningen",
	"B58":     "Sicilian, classical",
	"B59":     "Sicilian, Boleslavsky variation, 7. Nb3",
	"B60":     "Sicilian, Richter-Rauzer",
	"B61":     "Sicilian, Richter-Rauzer, Larsen variation",
	"B62":     "Sicilian, Richter-Rauzer, 6 ...e6",
	"B63":     "Sicilian, Richter-Rauzer, Rauzer attack",
	"B64":     "Sicilian, Richter-Rauzer, Rauzer attack, 7 ...Be7 defence, 9. f4",
	"B65":     "Sicilian, Richter-Rauzer, Rauzer attack, 7 ...Be7 defence, 9. ...Nxd4",
	"B66":     "Sicilian, Richter-Rauzer, Rauzer attack, 7 ...a6",
	"B67":     "Sicilian, Richter-Rauzer, Rauzer attack, 7 ...a6 defence, 8 ...Bd7",
	"B68":     "Sicilian, Richter-Rauzer, Rauzer attack, 7 ...a6 defence, 9 ...Be7",
	"B69":     "Sicilian, Richter-Rauzer, Rauzer attack, 7 ...a6 defence, 11. Bxf6",
	"B70":     "Sicilian, dragon variation",
	"B71":     "Sicilian, dragon, Levenfish variation",
	"B72":     "Sicilian, dragon, 6. Be3",
	"B73":     "Sicilian, dragon, classical, 8. O-O",
	"B74":     "Sicilian, dragon, classical, 9. Nb3",
	"B75":     "Sicilian, dragon, Yugoslav attack",
	"B76":     "Sicilian, dragon, Yugoslav attack, 7 ...O-O",
	"B77":     "Sicilian, dragon, Yugoslav attack, 9. Bc4",
	"B78":     "Sicilian, dragon, Yugoslav attack, 10. O-O-O",
	"B79":     "Sicilian, dragon, Yugoslav attack, 12. h4",
	"B80":     "Sicilian, Scheveningen variation",
	"B81":     "Sicilian, Scheveningen, Keres attack",
	"B82":     "Sicilian, Scheveningen, 6. f4",
	"B83":     "Sicilian, Scheveningen, 6. Be2",
	"B84":     "Sicilian, Scheveningen, classical variation",
	"B85":     "Sicilian, Scheveningen, classical variation with ...Qc7 and ...Nc6",
	"B86":     "Sicilian, Sozin attack",
	"B87":     "Sicilian, Sozin with ...a6 and ...b5",
	"B88":     "Sicilian, Sozin, Leonhardt variation",
	"B89":     "Sicilian, Sozin, 7. Be3",
	"B90":     "Sicilian, Najdorf",
	"B91":     "Sicilian, Najdorf, Zagreb (fianchetto) variation",
	"B92":     "Sicilian, Najdorf, Opovcensky variation",
	"B93":     "Sicilian, Najdorf, 6. f4",
	"B94":     "Sicilian, Najdorf, 6. Bg5",
	"B95":     "Sicilian, Najdorf, 6 ...e6",
	"B96":     "Sicilian, Najdorf, 7. f4",
	"B97":     "Sicilian, Najdorf, 7 ...Qb7",
	"B98":     "Sicilian, Najdorf, 7 ...Be7",
	"B99":     "Sicilian, Najdorf, 7 ...Be7 main line",
	"C00":     "French defence",
	"C01":     "French defence, exchange variation",
	"C02":     "French defence, advance variation",
	"C03":     "French defence, Tarrasch",
	"C04":     "French defence, Tarrasch, Guimard main line",
	"C05":     "French defence, Tarrasch, closed variation",
	"C06":     "French defence, Tarrasch, closed variation, main line",
	"C07":     "French defence, Tarrasch, open variation",
	"C08":     "French defence, Tarrasch, open, 4. exd5 exd5",
	"C09":     "French defence, Tarrasch, open variation, main line",
	"C10":     "French defence, Paulsen variation",
	"C11":     "French defence",
	"C12":     "French defence, MacCutcheon variation",
	"C13":     "French defence, classical",
	"C14":     "French defence, classical",
	"C15":     "French defence, Winawer (Nimzovich) variation",
	"C16":     "French defence, Winawer, advance variation",
	"C17":     "French defence, Winawer, advance variation",
	"C18":     "French defence, Winawer, advance variation",
	"C19":     "French defence, Winawer, advance variation",
	"C20":     "King's pawn game",
	"C21":     "Centre game",
	"C22":     "Centre game",
	"C23":     "Bishop's opening",
	"C24":     "Bishop's opening",
	"C25":     "Vienna game",
	"C26":     "Vienna, Falkbeer variation",
	"C27":     "Vienna game",
	"C28":     "Vienna game",
	"C29":     "Vienna gambit",
	"C30":     "King's gambit",
	"C31":     "King's gambit declined, falkbeer, counter-gambit",
	"C32":     "King's gambit declined, falkbeer, 5.dxe4",
	"C33":     "King's Gambit accepted",
	"C34":     "King's Gambit accepted",
	"C35":     "King's Gambit accepted, Cunningham defence",
	"C36":     "King's Gambit accepted, Abbazia defence",
	"C37":     "King's Gambit accepted, Quaade gambit",
	"C38":     "King's Gambit accepted",
	"C39":     "King's Gambit accepted",
	"C40":     "King's knight opening",
	"C41":     "Philidor's defence",
	"C42":     "Petrov",
	"C43":     "Petrov, modern (Steinitz) attack",
	"C44":     "King's pawn game",
	"C45":     "Scotch game",
	"C46":     "Three knights game",
	"C47":     "Four knights, Scotch variation",
	"C48":     "Four knights, Spanish variation",
	"C49":     "Four knights, double Ruy Lopez",
	"C50":     "Italian",
	"C51":     "Evans gambit declined",
	"C52":     "Evans gambit",
	"C53":     "Giuoco Piano",
	"C54":     "Giuoco Piano",
	"C55":     "Two knights defence",
	"C56":     "Two knights defence; 4. d4 exd5 ; 5. O-O Nxe4",
	"C57":     "Two knights defence; 4. Ng5",
	"C58":     "Two knights defence; 4. Ng5 d5 ; 5. exd5 Na5",
	"C59":     "Two knights defence; 4. Ng5 d5 ; 5. exd5 Na5 ; 6. Bb5+ c6; 7. dxc6 bxc6 ; 8. Be2 h6",
	"C60":     "Ruy Lopez (Spanish opening)",
	"C61":     "Ruy Lopez, Bird's defence",
	"C62":     "Ruy Lopez, old Steinitz defence",
	"C63":     "Ruy Lopez, Schliemann defence",
	"C64":     "Ruy Lopez, classical (Cordel) defence",
	"C65":     "Ruy Lopez, Berlin defence",
	"C66":     "Ruy Lopez, Berlin defence",
	"C67":     "Ruy Lopez, Berlin defence",
	"C68":     "Ruy Lopez, exchange variation",
	"C69":     "Ruy Lopez, exchange variation",
	"C70":     "Ruy Lopez",
	"C71":     "Ruy Lopez, modern Steinitz variation",
	"C72":     "Ruy Lopez, modern Steinitz variation",
	"C73":     "Ruy Lopez, modern Steinitz variation",
	"C74":     "Ruy Lopez, modern Steinitz variation",
	"C75":     "Ruy Lopez, modern Steinitz variation",
	"C76":     "Ruy Lopez, modern Steinitz variation",
	"C77":     "Ruy Lopez, Morphy defence",
	"C78":     "Ruy Lopez, 5. O-O",
	"C79":     "Ruy Lopez, Steinitz defence deferred (Russian defence)",
	"C80":     "Ruy Lopez, open",
	"C81":     "Ruy Lopez, open",
	"C82":     "Ruy Lopez, open",
	"C83":     "Ruy Lopez, open",
	"C84":     "Ruy Lopez, closed defence",
	"C85":     "Ruy Lopez, exchange variation, doubly deferred (DERLD)",
	"C86":     "Ruy Lopez, Worrall attack",
	"C87":     "Ruy Lopez, closed, Averbach variation",
	"C88":     "Ruy Lopez, closed",
	"C89":     "Ruy Lopez, Marshall counter-attack",
	"C90":     "Ruy Lopez, closed",
	"C91":     "Ruy Lopez, closed",
	"C92":     "Ruy Lopez, closed",
	"C93":     "Ruy Lopez, closed",
	"C94":     "Ruy Lopez, closed",
	"C95":     "Ruy Lopez, closed",
	"C96":     "Ruy Lopez, closed",
	"C97":     "Ruy Lopez, closed",
	"C98":     "Ruy Lopez, closed",
	"C99":     "Ruy Lopez, closed",
	"D00":     "Queen's pawn game",
	"D01":     "Richter-Veresov attack",
	"D02":     "Queen's pawn game",
	"D03":     "Torre attack (Tartakower variation)",
	"D04":     "Queen's pawn game",
	"D05":     "Queen's pawn game",
	"D06":     "Queen's Gambit",
	"D07":     "Queen's Gambit Declined, Chigorin defence",
	"D08":     "Queen's Gambit Declined, Albin counter-gambit",
	"D09":     "Queen's Gambit Declined, Albin counter-gambit, 5. g3",
	"D10":     "Queen's Gambit Declined Slav defence",
	"D11":     "Queen's Gambit Declined Slav defence, 3. Nf3",
	"D12":     "Queen's Gambit Declined Slav defence, 4. e3 Bf5",
	"D13":     "Queen's Gambit Declined Slav defence, exchange variation",
	"D14":     "Queen's Gambit Declined Slav defence, exchange variation, 6. Bf4 Bf5",
	"D15":     "Queen's Gambit Declined Slav defence, 4. Nc3",
	"D16":     "Queen's Gambit Declined Slav accepted",
	"D17-D19": "Queen's Gambit Declined Slav, Czech defence",
	"D20":     "Queen's gambit accepted",
	"D21":     "Queen's gambit accepted, 3. Nf3",
	"D22":     "Queen's gambit accepted, Alekhine defence",
	"D23":     "Queen's gambit accepted",
	"D24":     "Queen's gambit accepted, 4. Nc3",
	"D25":     "Queen's gambit accepted, 4. e3",
	"D26":     "Queen's gambit accepted, 4 ...e6",
	"D27":     "Queen's gambit accepted, classical, 6 ...a6",
	"D28":     "Queen's gambit accepted, classical, 7. Qe2",
	"D29":     "Queen's gambit accepted, classical, 8 ...Bb7",
	"D30":     "Queen's gambit declined",
	"D31":     "Queen's gambit declined, 3. Nc3",
	"D32":     "Queen's gambit declined, Tarrasch defence",
	"D33":     "Queen's gambit declined, Tarrasch, Schlechter-Rubinstein system",
	"D34":     "Queen's gambit declined, Tarrasch, Prague variation, 7 ...Be7",
	"D35":     "Queen's gambit declined, 3 ...Nf6",
	"D36":     "Queen's gambit declined, exchange, positional line, 6. Qc2",
	"D37":     "Queen's gambit declined, 4. Nf3",
	"D38":     "Queen's gambit declined, Ragozin variation",
	"D39":     "Queen's gambit declined, Ragozin, Vienna variation",
	"D40":     "Queen's gambit declined, Semi-Tarrasch defence",
	"D41":     "Queen's gambit declined, Semi-Tarrasch defence, 5. cxd5",
	"D42":     "Queen's gambit declined, Semi-Tarrasch defence, 7. Bd3",
	"D43-D49": "Queen's Gambit Declined semi-Slav",
	"D50-D69": "Queen's Gambit Declined, 4.Bg5",
	"D70-D79": "Neo-Gruenfeld defence",
	"D80":     "Gruenfeld defence",
	"D81":     "Gruenfeld, Russian variation",
	"D82":     "Gruenfeld, 4. Bf4",
	"D83":     "Gruenfeld, Gruenfeld gambit",
	"D84":     "Gruenfeld, Gruenfeld gambit accepted",
	"D85":     "Gruenfeld, exchange variation",
	"D86":     "Gruenfeld, exchange variation, classical variation",
	"D87":     "Gruenfeld, exchange variation, Spassky variation",
	"D88":     "Gruenfeld, Spassky variation, main line, 10 ...cxd4, 11. cxd4",
	"D89":     "Gruenfeld, Spassky variation, main line, 13. Bd3",
	"D90":     "Gruenfeld, Three knights variation",
	"D91":     "Gruenfeld, 5. Bg5",
	"D92":     "Gruenfeld, 5. Bf4",
	"D93":     "Gruenfeld with Bf4 e3",
	"D94":     "Gruenfeld, 5. e3",
	"D95":     "Gruenfeld with e3 & Qb3",
	"D96":     "Gruenfeld, Russian variation",
	"D97":     "Gruenfeld, Russian variation with e4",
	"D98":     "Gruenfeld, Russian variation, Smyslov variation",
	"D99":     "Gruenfeld defence, Smyslov, main line",
	"E00":     "Queen's pawn game",
	"E01-E09": "Catalan, closed",
	"E10":     "Queen's pawn game",
	"E11":     "Bogo-Indian defence",
	"E12-E19": "Queen's Indian defence",
	"E20-E59": "Nimzo-Indian defence",
	"E60":     "King's Indian defence",
	"E61":     "King's Indian defence, 3. Nc3",
	"E62":     "King's Indian defence, fianchetto variation",
	"E63":     "King's Indian defence, fianchetto variation",
	"E64":     "King's Indian defence, fianchetto variation",
	"E65":     "King's Indian defence, fianchetto variation",
	"E66":     "King's Indian defence, fianchetto variation",
	"E67":     "King's Indian defence, fianchetto variation",
	"E68":     "King's Indian defence, fianchetto variation",
	"E69":     "King's Indian defence, fianchetto variation",
	"E70":     "King's Indian, 4. e4",
	"E71":     "King's Indian, Makagonov system (5. h3)",
	"E72":     "King's Indian with e4 & g3",
	"E73":     "King's Indian, 5. Be2",
	"E74":     "King's Indian, Averbakh",
	"E75":     "King's Indian, Averbakh",
	"E76":     "King's Indian, Four pawns attack",
	"E77":     "King's Indian, Four pawns attack",
	"E78":     "King's Indian, Four pawns attack",
	"E79":     "King's Indian, Four pawns attack",
	"E80":     "King's Indian, Saemisch variation",
	"E81":     "King's Indian, Saemisch variation",
	"E82":     "King's Indian, Saemisch variation",
	"E83":     "King's Indian, Saemisch variation",
	"E84":     "King's Indian, Saemisch variation",
	"E85":     "King's Indian, Saemisch variation",
	"E86":     "King's Indian, Saemisch variation",
	"E87":     "King's Indian, Saemisch variation",
	"E88":     "King's Indian, Saemisch variation",
	"E89":     "King's Indian, Saemisch variation",
	"E90":     "King's Indian, 5. Nf3",
	"E91":     "King's Indian, 6. Be2",
	"E92":     "King's Indian, classical variation",
	"E93":     "King's Indian, Petrosian system, main line",
	"E94":     "King's Indian, orthodox variation",
	"E95":     "King's Indian, orthodox variation",
	"E96":     "King's Indian, orthodox variation",
	"E97":     "King's Indian, orthodox variation",
	"E98":     "King's Indian, orthodox variation",
	"E99":     "King's Indian, orthodox variation",
}
